color: lime
description: 'Call to Action Buttons'
fieldLayouts:
  284fee46-1054-4234-8001-ff87c807d25e:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-07-13T08:41:00+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 03b7685d-73fa-4b4f-a609-d5992cfc7439
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-13T08:43:19+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a580fa9f-fec5-4030-9ec4-056fa41939f4 # Plain Text 
            handle: linkText
            includeInCards: false
            instructions: null
            label: 'Link text'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 76a53286-b93a-4b66-9d77-ddb2969e8c68
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-13T08:43:19+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 2c90d339-319f-41d1-96cf-1c889863fef2 # URL
            handle: urlAddress
            includeInCards: false
            instructions: null
            label: 'URL Address'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a86d2f56-503c-484d-b4f7-1696b74f75f5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-13T08:43:19+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: bb28314d-a061-45be-bebf-8b0a6076b3d0 # Button Type
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 49bc446c-2f5a-4b23-aa14-dd181cc323fa
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4ef4da52-7b07-41d3-954d-69824cbcd2f3
        userCondition: null
handle: callToAction
hasTitleField: true
icon: link
name: 'Call to Action'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
