color: null
description: null
fieldLayouts:
  2b244306-a1c5-4527-8693-1185df6923d2:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-07-10T13:33:21+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 16fb0f7f-a335-47b0-a9ca-a3d233a767f4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-12T14:31:17+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a580fa9f-fec5-4030-9ec4-056fa41939f4 # Plain Text 
            handle: headlineLineOne
            includeInCards: false
            instructions: 'The first line from the headline of the homepage'
            label: Headline
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a6adc52c-67b8-4596-9603-06a83b9fab8f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-12T14:31:17+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a580fa9f-fec5-4030-9ec4-056fa41939f4 # Plain Text 
            handle: headlineLineTwo
            includeInCards: false
            instructions: 'Line two of the headline of the homepage (the gradient animation part)'
            label: 'Headline Line Two'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f8e43b78-6014-43e5-8899-804e2e660fbf
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-13T07:56:45+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 33dabbd5-4d93-4868-bee3-62998def8ddc # Text Area
            handle: heroDescription
            includeInCards: false
            instructions: 'Appears under the hero image headline.'
            label: 'Hero description'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1337744c-dd1f-4322-b151-d80f7bb95060
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-12T14:31:17+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3d54c233-d443-46e3-8ec7-850ab1c9d69a # Image
            handle: heroVideo
            includeInCards: false
            instructions: null
            label: Video
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4326a0e4-0443-499b-a957-73bf4ee9affe
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-13T08:57:13+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ad06897a-3f68-4e59-8dd8-6a551c070e88 # Call to Action
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4ef01fcf-9e33-4ea1-a290-db41df6fefa8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8a1ca38c-100e-4b55-b294-6d95ddbd5182
        userCondition: null
handle: homepage
hasTitleField: true
icon: house
name: Homepage
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{headline}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
